We have logged in as Captain Bot#2702
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "captainbot.py", line 182, in on_message
    await addemoji(attachment.url,message)
  File "captainbot.py", line 135, in addemoji
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 378, in dispatch
    result = condition(*args)
  File "captainbot.py", line 135, in <lambda>
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
AttributeError: 'NoneType' object has no attribute 'message_id'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "captainbot.py", line 182, in on_message
    await addemoji(attachment.url,message)
  File "captainbot.py", line 135, in addemoji
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 378, in dispatch
    result = condition(*args)
  File "captainbot.py", line 135, in <lambda>
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
AttributeError: 'NoneType' object has no attribute 'message_id'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "captainbot.py", line 182, in on_message
    await addemoji(attachment.url,message)
  File "captainbot.py", line 135, in addemoji
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 378, in dispatch
    result = condition(*args)
  File "captainbot.py", line 135, in <lambda>
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
AttributeError: 'NoneType' object has no attribute 'message_id'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "captainbot.py", line 182, in on_message
    await addemoji(attachment.url,message)
  File "captainbot.py", line 135, in addemoji
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 378, in dispatch
    result = condition(*args)
  File "captainbot.py", line 135, in <lambda>
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
AttributeError: 'NoneType' object has no attribute 'message_id'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "captainbot.py", line 182, in on_message
    await addemoji(attachment.url,message)
  File "captainbot.py", line 135, in addemoji
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 378, in dispatch
    result = condition(*args)
  File "captainbot.py", line 135, in <lambda>
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
AttributeError: 'NoneType' object has no attribute 'message_id'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "captainbot.py", line 182, in on_message
    await addemoji(attachment.url,message)
  File "captainbot.py", line 135, in addemoji
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 378, in dispatch
    result = condition(*args)
  File "captainbot.py", line 135, in <lambda>
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
AttributeError: 'NoneType' object has no attribute 'message_id'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "captainbot.py", line 182, in on_message
    await addemoji(attachment.url,message)
  File "captainbot.py", line 135, in addemoji
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 378, in dispatch
    result = condition(*args)
  File "captainbot.py", line 135, in <lambda>
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
AttributeError: 'NoneType' object has no attribute 'message_id'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "captainbot.py", line 182, in on_message
    await addemoji(attachment.url,message)
  File "captainbot.py", line 135, in addemoji
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 378, in dispatch
    result = condition(*args)
  File "captainbot.py", line 135, in <lambda>
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
AttributeError: 'NoneType' object has no attribute 'message_id'
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "captainbot.py", line 182, in on_message
    await addemoji(attachment.url,message)
  File "captainbot.py", line 135, in addemoji
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
  File "/usr/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 378, in dispatch
    result = condition(*args)
  File "captainbot.py", line 135, in <lambda>
    msg = await bot.wait_for('message', check = lambda i : i.reference.message_id == msgb.id)
AttributeError: 'NoneType' object has no attribute 'message_id'
We have logged in as Captain Bot#2702
We have logged in as Captain Bot#2702
